version: '3.9'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourPassword123
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: torc.ui/Dockerfile  
    ports:
      - 5000:80
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDatabaseName;User=sa;Password=YourPassword123

volumes:
  dbdata: